### ISSUE TITLE
Sass Error in `harp compile` command

### ISSUE THREAD

**Issue by Xixiao007** [toolsday/toolsday#53]
Hello Una and Chris,

I cloned the latest code and use `harp compile _harp --output ../www` command to build static site.

My environment
- Node version: 5.1.1, 
- npm version: 3.3.12
- harp version: 0.21.0-pre.1

This command used to work well, but not anymore with error below:

```
{
  "source": "Sass",
  "dest": "CSS",
  "filename": "/home/finxxi/Dropbox/repos/websites/test/_harp/css/_layout.scss",
  "lineno": 59,
  "name": "Sass Error",
  "message": "\".sm-contain\" failed to @extend \"%max-800\".\nThe selector \"%max-800\" was not found.\nUse \"@extend %max-800 !optional\" if the extend should be able to fail.",
  "stack": "// setup\n@import 'reset';\n@import 'color';\n@import 'type';\n@import 'body';\n@import 'layout';\n\n// regions\n@import 'header';\n@import 'home';\n@import 'footer';\n\n//pages\n@import 'episode';\n@import 'about';\n@import 'error';"
}
```

**Comment by una** [comment]
we're using harp version `0.20.3` like in the package.json -- do you still get the same error?

**Comment by Xixiao007** [comment]
ahh, yes the harp version resolved my problem

I uninstall harp and reinstall by `npm install -g harp@0.20.3 , no error anymore! Thanks Una and keep up with Toolsday shows, it is so much fun listening to you two.

**Comment by una** [comment]
Thanks for listening!
